### ISSUE TITLE
County undefined

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/cecdss#107] opened 2021-09-14 16:15 UTC
When clicking on a cluster county comes back as "undefined". However I think ever pixel should have county data, so try to figure out why it's not loading.

![image](https://user-images.githubusercontent.com/202753/133295040-40cb46a7-a17a-4756-aa69-37dac4d71fd7.png)

**Comment by wongband** [comment] 2021-09-15 19:25
From what I noticed, the `county` field is not being returned from the api in yearlyResult
<img width="566" alt="Screen Shot 2021-09-15 at 12 24 52 PM" src="https://user-images.githubusercontent.com/35946905/133496684-24c5f20f-48b7-443f-ab40-84c6ed59fe47.png">

**Comment by kaiyanl** [comment] 2021-11-06 01:57
@srkirkland I tried printing out the county name of a cluster right after [getClusters](https://github.com/ucdavis/cecdss-backend/blob/master/processYear.ts#L117), and the county name was undefined. It seems that the cause is in our database.

**Comment by kaiyanl** [comment] 2021-11-09 23:18
resolved via ucdavis/cecdss-backend#77

**Closed by kaiyanl** 2021-11-09 23:18 UTC
